### ISSUE TITLE
Cookie auth0.is.authenticated will be soon rejected

### ISSUE THREAD

**Issue by avanzal** [auth0/auth0-spa-js#459]
### Description

The developer console shows a warning that the auth0.is.authenticated cookie will be rejected in future browser versions. This cookie is set when the app calls `getTokenSilently`, `loginWithPopup`, or `handleRedirectCallback`.

In Firefox:

> Cookie “auth0.is.authenticated” will be soon rejected because it has the “sameSite” attribute set to “none” or an invalid value, without the “secure” attribute. To know more about the “sameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Cookies

In Chrome:

> A cookie associated with a cross-site resource at http://auth0.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.

![image](https://user-images.githubusercontent.com/6913338/81659185-0df8a800-946c-11ea-8164-53b9b446f226.png)

I believe this is due to the way the library is setting the auth0.is.authenticated cookie. It is not passing the `secure` or `sameSite` parameters to the downstream es-cookie `set` method

In _src/Auth0Client.ts_:
```
ClientStorage.save('auth0.is.authenticated', true, { daysUntilExpire: 1 });
```

and in _src/storage.ts_:
```
export const save = (
  key: string,
  value: any,
  options: ClientStorageOptions
) => {
  Cookies.set(key, JSON.stringify(value), {
    expires: options.daysUntilExpire
  });
};
```

### Reproduction

Have the developer console open while your app calls Auth0Client's `getTokenSilently`, `loginWithPopup`, or `handleRedirectCallback`.

### Environment

- **Version of this library used:** @auth0/auth0-spa-js@1.8.1
- **Version of the platform or framework used, if applicable:**
- **Other relevant versions (language, server software, OS, browser):** Firefox latest (76), Chrome latest

**Comment by adamjmcgrath** [comment]
Hey @avanzal - thanks for raising this

For the warning you're seeing in Chrome - this is a warning about auth0.com's cookie and Chrome's upcoming ITP feature - more info here https://github.com/auth0/auth0-spa-js/issues/425#issuecomment-615232166

For the warning you're seeing in Firefox - I'm not able to reproduce this, which version of FF are you using? And are you on localhost or https?

**Comment by avanzal** [comment]
Hi @adamjmcgrath ,

Both message seem to be talking about the same thing. I believe both Chrome and Firefox are implementing the same security changes with regards to the sameSite and secure cookie options.

To answer your queries:
- I'm on the latest Firefox (76.0.1), latest Chrome (81.0.4044.138), and the latest auth0-spa-js (1.8.1).
- My localhost setup is running https, but I also see the same problem on my hosted version of the app.

The error appears to happen right after the call to _src/index.ts_ `createAuth0Client(...)` after a page reload, which in turn calls `getTokenSilently()` which sets the _auth0.is.authenticated_ cookie with `SameSite=None` and `secure=false` - therefore triggering the warning message.

**Comment by stevehobbsdev** [comment]
@avanzal Let's be clear - are you talking about an error or a warning?

I don't believe there will be a problem with the running of your app, aside from getting a warning in the console. The cookie is set by our JavaScript SDK and is only read by our JavaScript SDK and so in practise is not affected by SameSite, which only affects the server's ability to read cookies.

We can of course look at options, including the possibility of using local storage to store this flag.

**Comment by avanzal** [comment]
Hey @stevehobbsdev, it's currently a warning. Other than simply wanting to eliminate security-related warnings in my app, one concern here is that the warning (and corresponding draft spec from Google) seem to indicate that the way this library is setting this cookie will stop working at some point in the future.

**Comment by submarines-and** [comment]
You can enable this behavior now with a flag, for me it still worked with the flag on.

![image](https://user-images.githubusercontent.com/3114694/81714202-1b675f80-9477-11ea-9d0e-991d2cef2f76.png)

**Comment by stevehobbsdev** [comment]
@avanzal I think there is a couple of things going on here.

In Chrome, you are getting the warning because of a compatibility cookie that we set for older browsers that do not support the SameSite attribute. This is an Auth0 Server concern and out of scope of this SDK (i.e. nothing we can can change here). Either way, it is a warning that can be ignored as far as whether your app will break goes. You can test this out (if you haven't already) by enabling the SameSite flags in `chrome://flags` - you should find that everything still works as normal.

The warning in Firefox is about auth state cookie that we set from the SDK (I've managed to reproduce this now). However, the cookie is designed to be written and read by JavaScript (Firefox doesn't know our intended usage), which is unaffected by the SameSite changes. Thus again, everything should still work.

However, the spec indicating that the cookie will be _removed_ is concerning and something we'll take on board to investigate and mitigate against.

**Comment by ties-v** [comment]
In local development I've encountered the same warning (Firefox 76, on a localhost dev server). A bit more info is available at [here](https://web.dev/samesite-cookies-explained/#changes-to-the-default-behavior-without-samesite).

This is probably only a development issue, as (in my case) the app is served over http. But is it not possible to include `SameSite=Lax` or `SameSite=Strict` for this cookie? It is only used by the spa application to remember some state - at least, that is how I understand it. 

This GIF shows that only for `SameSite=None` this warning appears:
![cookie SameSite](https://user-images.githubusercontent.com/1744962/81907226-b53e2200-95c7-11ea-8d7b-91eabf74cdc1.gif)

**Comment by stevehobbsdev** [comment]
@ties-v Yes that would be an option here - these cookies are only for the client side anyway.

**Comment by rumsrami** [comment]
I am still getting this message in firefox over https

**Comment by stevehobbsdev** [comment]
@rumsrami Do you still see this if you log out and then log back in again? Just wondering if this cookie has existed since before you updated (I'm assuming you've updated to the latest release).

**Comment by rumsrami** [comment]
Yes it is still there, this is from my yarn.lock file.
`"@auth0/auth0-spa-js@^1.9.0":
  version "1.10.0"
  resolved "https://registry.yarnpkg.com/@auth0/auth0-spa-js/-/auth0-spa-js-1.10.0.`

**Comment by stevehobbsdev** [comment]
Ok, digging into this, [Firefox still does not set `Lax` by default](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite) when you do not specify the `SameSite` attribute when creating cookies, it will continue to set `None` (but then display a warning about it). However, this is behind a Firefox configuration flag (`network.cookie.samesite.laxbydefault`) and presumably they will enable this flag by default in future versions, just like most of the other modern browsers have done.

For now, the warning is just a warning and you can turn the flag on to verify that your application still works as intended. The warning will start to disappear in future versions of Firefox.

So, we believe that what we've done with SameSite in this SDK aligns with where browsers are going in this regard, even if the warning in the interim is not ideal.

**Comment by rumsrami** [comment]
but is this the intended way to work that I can read both cookies in the console using document.cookie. I am not a security expert so i dont really know the best practice.

**Comment by stevehobbsdev** [comment]
Yes that's fine. The cookies are created by the client-side SDK for the purposes of being able to access them from JavaScript, so it makes sense you can access them using the method you've shown. There is nothing sensitive in these cookies.

**Comment by rumsrami** [comment]
Great, thanks a lot for the clarification.
